### ISSUE TITLE
Disable pinching

### ISSUE THREAD

**Issue by velograph** [needmore/scratch#11]
`<meta name="viewport" content="width=device-width, initial-scale=1">` 
should also have
 `user-scalable=no"`

to keep the user from pinching and zooming on small devices.

**Comment by brigleb** [comment]
Make it a pull request, @velograph !!!

**Comment by velograph** [comment]
Well it would have been hella smart for me to be in the correct branch when doing this. Because I was on master, there's no pull request. 

Lesson learned!

For my next trick, I'll be sure to be on a feature branch (probably named after the issue I'm working on) which will make pull requesting and merging easier.
