### ISSUE TITLE
Load web fonts responsibly

### ISSUE THREAD

**Issue by gregorholzmann** [needmore/scratch#16]
Since I didn't get a chance to make a contribution to this repo on Friday, I'll give this issue a go on Tuesday. Is this something we want standard in every custom theme we develop or should we consider this on a case-by-case basis? What is the most efficient way to do this while avoiding any and all FOUTs?

Possibly using some resources from this article @brigleb posted in dev chat: 
http://www.filamentgroup.com/lab/font-loading.html

**Comment by brigleb** [comment]
@gregorholtz this is stuff to be tackled on Fridays, so today is a no-go.

I do think it's worthwhile to tackle, but there are probably smaller and more pressing issues in here, so maybe we should talk on Friday?
