### ISSUE TITLE
Integrate Bourbon and Neat

### ISSUE THREAD

**Issue by brigleb** [needmore/scratch#2]
[Bourbon](http://bourbon.io) is nice for what it gives us in terms of the helpers, and [Neat](http://neat.bourbon.io) is the grid system we'd like to be using.

I would suggest looking at the [some like it neat](https://github.com/digisavvy/some-like-it-neat) project to see how they put all of these pieces together.

We don't really want Bitters, and I could see us just wanting to use Refills on an ad-hoc basis.

**Comment by brigleb** [comment]
@devasaur it seems like you just did this for DGW, perhaps you would be the right person to add it here since you know kind of how it should work.

**Comment by velograph** [comment]
BTW, I created a pull request for this issue. [It can be seen here] (https://github.com/needmore/scratch/pull/20)

**Comment by velograph** [comment]
The pull request is simply for installing the bourbon and neat folders. I didn't include the Bourbon/Neat references in the style.scss file. I also think adding a watch task to the Gruntfile for any changes to the Bourbon or Neat directories. (Changing breakpoints, container width, etc)
