### ISSUE TITLE
Clarify and codify image handling

### ISSUE THREAD

**Issue by velograph** [needmore/scratch#9]
It seems like we're always struggling to make images behave correctly. We have some solutions that involve serving Retina images when needed (Retina2x plugin), but aside from that, Wordpress is still serving large images to small devices.

We need a way to define our image sizes dependent on the project, but serve the appropriate size depending on the device width. 

Suggested reading: 

1. http://www.elegantthemes.com/blog/tips-tricks/integrate-picturefill-with-wordpress-and-make-images-responsive
2. https://wordpress.org/plugins/picturefillwp/
3. https://github.com/kylereicks/picturefill.js.wp/tree/master
4. http://css-tricks.com/hassle-free-responsive-images-for-wordpress/

**Comment by brigleb** [comment]
One thing that we basically concluded the other day is that we need to focus on having 1x assets defined in WordPress, and then have other tools, polyfills, whatever handling the 2x. Is this right @velograph? If so, we should plan this a bit more.

**Comment by velograph** [comment]
Further reading I'm doing to get a better understanding of how to solve this:

1. http://code.tutsplus.com/tutorials/ensuring-your-theme-has-retina-support--wp-33430
2. http://www.presscoders.com/2012/10/how-to-make-your-wordpress-theme-retina-ready/
3. http://wplift.com/make-wordpress-themes-retina-display-ready
4. http://premium.wpmudev.org/blog/wordpress-retina/

Each of these differ a bit. I'm beginning to feel like our solution for this needs to be home rolled and not rely on a plugin to work. The Retina plugin we've been using doesn't seem to work all the time which adds more confusion.

The search goes on...

**Comment by brigleb** [comment]
Also note #23 which requires us to add a polyfill for now.
